// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SOURCEMAPSCHEMA_SOURCEMAPSCHEMA_H_
#define FLATBUFFERS_GENERATED_SOURCEMAPSCHEMA_SOURCEMAPSCHEMA_H_

#include "flatbuffers/flatbuffers.h"

namespace SourceMapSchema {

struct Mapping;

struct Map;
struct MapBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Mapping FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t generatedLine_;
  int32_t generatedColumn_;
  int32_t originalLine_;
  int32_t originalColumn_;
  int32_t source_;
  int32_t name_;

 public:
  Mapping() {
    memset(static_cast<void *>(this), 0, sizeof(Mapping));
  }
  Mapping(int32_t _generatedLine, int32_t _generatedColumn, int32_t _originalLine, int32_t _originalColumn, int32_t _source, int32_t _name)
      : generatedLine_(flatbuffers::EndianScalar(_generatedLine)),
        generatedColumn_(flatbuffers::EndianScalar(_generatedColumn)),
        originalLine_(flatbuffers::EndianScalar(_originalLine)),
        originalColumn_(flatbuffers::EndianScalar(_originalColumn)),
        source_(flatbuffers::EndianScalar(_source)),
        name_(flatbuffers::EndianScalar(_name)) {
  }
  int32_t generatedLine() const {
    return flatbuffers::EndianScalar(generatedLine_);
  }
  int32_t generatedColumn() const {
    return flatbuffers::EndianScalar(generatedColumn_);
  }
  int32_t originalLine() const {
    return flatbuffers::EndianScalar(originalLine_);
  }
  int32_t originalColumn() const {
    return flatbuffers::EndianScalar(originalColumn_);
  }
  int32_t source() const {
    return flatbuffers::EndianScalar(source_);
  }
  int32_t name() const {
    return flatbuffers::EndianScalar(name_);
  }
};
FLATBUFFERS_STRUCT_END(Mapping, 24);

struct Map FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MapBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAMES = 4,
    VT_SOURCES = 6,
    VT_MAPPINGS = 8
  };
  int32_t names() const {
    return GetField<int32_t>(VT_NAMES, 0);
  }
  int32_t sources() const {
    return GetField<int32_t>(VT_SOURCES, 0);
  }
  const flatbuffers::Vector<const SourceMapSchema::Mapping *> *mappings() const {
    return GetPointer<const flatbuffers::Vector<const SourceMapSchema::Mapping *> *>(VT_MAPPINGS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_NAMES) &&
           VerifyField<int32_t>(verifier, VT_SOURCES) &&
           VerifyOffset(verifier, VT_MAPPINGS) &&
           verifier.VerifyVector(mappings()) &&
           verifier.EndTable();
  }
};

struct MapBuilder {
  typedef Map Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_names(int32_t names) {
    fbb_.AddElement<int32_t>(Map::VT_NAMES, names, 0);
  }
  void add_sources(int32_t sources) {
    fbb_.AddElement<int32_t>(Map::VT_SOURCES, sources, 0);
  }
  void add_mappings(flatbuffers::Offset<flatbuffers::Vector<const SourceMapSchema::Mapping *>> mappings) {
    fbb_.AddOffset(Map::VT_MAPPINGS, mappings);
  }
  explicit MapBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MapBuilder &operator=(const MapBuilder &);
  flatbuffers::Offset<Map> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Map>(end);
    return o;
  }
};

inline flatbuffers::Offset<Map> CreateMap(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t names = 0,
    int32_t sources = 0,
    flatbuffers::Offset<flatbuffers::Vector<const SourceMapSchema::Mapping *>> mappings = 0) {
  MapBuilder builder_(_fbb);
  builder_.add_mappings(mappings);
  builder_.add_sources(sources);
  builder_.add_names(names);
  return builder_.Finish();
}

inline flatbuffers::Offset<Map> CreateMapDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t names = 0,
    int32_t sources = 0,
    const std::vector<SourceMapSchema::Mapping> *mappings = nullptr) {
  auto mappings__ = mappings ? _fbb.CreateVectorOfStructs<SourceMapSchema::Mapping>(*mappings) : 0;
  return SourceMapSchema::CreateMap(
      _fbb,
      names,
      sources,
      mappings__);
}

inline const SourceMapSchema::Map *GetMap(const void *buf) {
  return flatbuffers::GetRoot<SourceMapSchema::Map>(buf);
}

inline const SourceMapSchema::Map *GetSizePrefixedMap(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<SourceMapSchema::Map>(buf);
}

inline bool VerifyMapBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SourceMapSchema::Map>(nullptr);
}

inline bool VerifySizePrefixedMapBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SourceMapSchema::Map>(nullptr);
}

inline void FinishMapBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<SourceMapSchema::Map> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMapBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<SourceMapSchema::Map> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace SourceMapSchema

#endif  // FLATBUFFERS_GENERATED_SOURCEMAPSCHEMA_SOURCEMAPSCHEMA_H_
